FROM apache/airflow:3.0.3 AS builder

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential gcc python3-dev \
    openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-postgres \
    pyspark==3.5.0

FROM apache/airflow:slim-3.0.3-python3.12

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
COPY --from=builder /usr/local /usr/local
